version: 2
updates:
  # Actualizar GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily" # Se cambiará a weekly después.
    open-pull-requests-limit: 5
    assignees:
      - "evaristogz"
      - "naesman1" 
      - "jpalenz77"
    commit-message:
      prefix: "ci"
      include: "scope"